.PHONY: clean All

All:
	@echo "----------Building project:[ Delivery - Debug ]----------"
	@cd "Delivery" && "$(MAKE)" -f  "Delivery.mk"
clean:
	@echo "----------Cleaning project:[ Delivery - Debug ]----------"
	@cd "Delivery" && "$(MAKE)" -f  "Delivery.mk" clean
